Repository jenkinsci/checks-api-plugin, pull requests merged in 2020-08, with the labels that each got.

#2 Enable Dependabot v2
  .github/dependabot.yml
Labels: chore

#4 Publish checks for job and use task listener
  src/main/java/io/jenkins/plugins/checks/BuildStatusChecksPublisher.java
  src/main/java/io/jenkins/plugins/checks/api/ChecksPublisher.java
  src/main/java/io/jenkins/plugins/checks/api/ChecksPublisherFactory.java
  src/test/java/io/jenkins/plugins/checks/api/ChecksPublisherFactoryITest.java
  src/test/java/io/jenkins/plugins/checks/api/ChecksPublisherFactoryTest.java
Labels: enhancement

#10 Enable an ArchUnit test that validates that there are no package cycles
  src/test/java/io/jenkins/plugins/checks/PackageArchitectureTest.java
  src/test/resources/design.puml
Labels: chore

#8 Add toString for api models
  src/main/java/io/jenkins/plugins/checks/api/ChecksAction.java
  src/main/java/io/jenkins/plugins/checks/api/ChecksAnnotation.java
  src/main/java/io/jenkins/plugins/checks/api/ChecksDetails.java
  src/main/java/io/jenkins/plugins/checks/api/ChecksImage.java
  src/main/java/io/jenkins/plugins/checks/api/ChecksOutput.java
  src/test/java/io/jenkins/plugins/checks/api/ChecksActionTest.java
  src/test/java/io/jenkins/plugins/checks/api/ChecksAnnotationTest.java
  src/test/java/io/jenkins/plugins/checks/api/ChecksDetailsTest.java
  src/test/java/io/jenkins/plugins/checks/api/ChecksImageTest.java
  src/test/java/io/jenkins/plugins/checks/api/ChecksOutputTest.java
Labels: chore, enhancement

#12 Map unstable build to check failure
  src/main/java/io/jenkins/plugins/checks/BuildStatusChecksPublisher.java
Labels: bug

#13 Listen to checkout instead of on started.
  src/main/java/io/jenkins/plugins/checks/BuildStatusChecksPublisher.java
Labels: enhancement

#15 Bump version of analysis-pom to 4.1.0 (and codingstyle to 1.4.0)
  etc/assertj-templates/assertions_entry_point_class_template.txt
  etc/assertj-templates/soft_assertions_entry_point_class_template.txt
  pom.xml
  src/main/java/io/jenkins/plugins/checks/BuildStatusChecksPublisher.java
  src/main/java/io/jenkins/plugins/checks/api/ChecksAction.java
  src/main/java/io/jenkins/plugins/checks/api/ChecksImage.java
Labels: chore

#7 Add pipeline support
  pom.xml
  src/main/java/io/jenkins/plugins/checks/BuildStatusChecksPublisher.java
  src/main/java/io/jenkins/plugins/checks/api/ChecksImage.java
  src/main/java/io/jenkins/plugins/checks/api/ChecksPublisher.java
  src/main/java/io/jenkins/plugins/checks/api/ChecksPublisherFactory.java
  src/main/java/io/jenkins/plugins/checks/steps/PublishChecksStep.java
  src/main/resources/io/jenkins/plugins/checks/steps/PublishChecksStep/config.jelly
  src/main/resources/io/jenkins/plugins/checks/steps/PublishChecksStep/config.properties
  src/main/resources/io/jenkins/plugins/checks/steps/PublishChecksStep/help-conclusion.html
  src/main/resources/io/jenkins/plugins/checks/steps/PublishChecksStep/help-detailsURL.html
  src/main/resources/io/jenkins/plugins/checks/steps/PublishChecksStep/help-name.html
  src/main/resources/io/jenkins/plugins/checks/steps/PublishChecksStep/help-status.html
  src/main/resources/io/jenkins/plugins/checks/steps/PublishChecksStep/help-summary.html
  src/main/resources/io/jenkins/plugins/checks/steps/PublishChecksStep/help-text.html
  src/main/resources/io/jenkins/plugins/checks/steps/PublishChecksStep/help-title.html
  src/test/java/io/jenkins/plugins/checks/api/ChecksImageTest.java
  src/test/java/io/jenkins/plugins/checks/api/NullChecksPublisherTest.java
  src/test/java/io/jenkins/plugins/checks/steps/PublishChecksStepITest.java
  src/test/java/io/jenkins/plugins/checks/steps/PublishChecksStepTest.java
  src/test/resources/design.puml
Labels: enhancement

#21 Add a new AssertJ template that does not produce deprecated warnings
  etc/assertj-templates/has_assertion_template.txt
Labels: chore
