Repository jenkinsci/checks-api-plugin, pull requests merged in 2020-12, with the labels that each got.

#49 Add withChecks step
  README.md
  docs/consumers-guide.md
  pom.xml
  src/main/java/io/jenkins/plugins/checks/steps/ChecksInfo.java
  src/main/java/io/jenkins/plugins/checks/steps/WithChecksStep.java
  src/main/java/io/jenkins/plugins/checks/steps/package-info.java
  src/main/resources/io/jenkins/plugins/checks/steps/WithChecksStep/config.jelly
  src/main/resources/io/jenkins/plugins/checks/steps/WithChecksStep/config.properties
  src/test/java/io/jenkins/plugins/checks/steps/WithChecksStepITest.java
  src/test/java/io/jenkins/plugins/checks/steps/WithChecksStepTest.java
Labels: enhancement

#57 Fix POM version and RevApi configuration
  pom.xml
Labels: bug

#52 Migrate to AbstractStatusChecksProperties class.
  src/main/java/io/jenkins/plugins/checks/status/AbstractStatusChecksProperties.java
  src/main/java/io/jenkins/plugins/checks/status/BuildStatusChecksPublisher.java
  src/main/java/io/jenkins/plugins/checks/status/StatusChecksProperties.java
Labels: chore

#55 Add capturing checks publisher, make publishChecks withChecksName aware
  docs/consumers-guide.md
  pom.xml
  src/main/java/io/jenkins/plugins/checks/steps/PublishChecksStep.java
  src/test/java/io/jenkins/plugins/checks/api/test/CapturingChecksPublisher.java
  src/test/java/io/jenkins/plugins/checks/steps/PublishChecksStepITest.java
  src/test/java/io/jenkins/plugins/checks/steps/WithChecksStepITest.java
Labels: tests

#58 Move CapturingChecksPublisher to util package.
  docs/consumers-guide.md
  pom.xml
  src/test/java/io/jenkins/plugins/checks/steps/PublishChecksStepITest.java
  src/test/java/io/jenkins/plugins/checks/steps/WithChecksStepITest.java
  src/test/java/io/jenkins/plugins/checks/util/CapturingChecksPublisher.java
Labels: chore, tests

#62 Jenkinsfile: only build on linux
  Jenkinsfile
Labels: chore

#59 Add LoggingChecksPublisher and tests for status checks
  src/test/java/io/jenkins/plugins/checks/status/BuildStatusChecksPublisherITest.java
  src/test/java/io/jenkins/plugins/checks/util/LoggingChecksPublisher.java
Labels: tests

#64 Handle abort differently from failures
  pom.xml
  src/main/java/io/jenkins/plugins/checks/steps/WithChecksStep.java
  src/test/java/io/jenkins/plugins/checks/steps/WithChecksStepITest.java
Labels: enhancement

#67 test> is not a scope...
  pom.xml
Labels: chore
