Repository jenkinsci/checks-api-plugin, pull requests merged in 2020-10, with the labels that each got.

#33 Remove missed beta restriction
  src/main/java/io/jenkins/plugins/checks/api/ChecksPublisherFactory.java
Labels: chore

#34 Update release drafter config
  .github/release-drafter.yml
Labels: chore

#40 Add JUnit plugin to the list of known Checks API consumers
  README.md
Labels: documentation

#41 Add Autograding plugin as a consumer
  README.md
Labels: chore

#31 Add the ability to allow users to customize status checks
  README.md
  docs/implementation-guide.md
  pom.xml
  src/main/java/io/jenkins/plugins/checks/status/BuildStatusChecksPublisher.java
  src/main/java/io/jenkins/plugins/checks/status/StatusChecksProperties.java
  src/main/java/io/jenkins/plugins/checks/status/package-info.java
  src/test/resources/design.puml
Labels: enhancement
