Repository jenkinsci/checks-api-plugin, pull requests merged in 2021-04, with the labels that each got.

#97 JENKINS-65262 Avoid holding queue lock when updating GitHub
  pom.xml
  spotbugs-exclusion-filter.xml
  src/main/java/io/jenkins/plugins/checks/status/BuildStatusChecksPublisher.java
  src/test/java/io/jenkins/plugins/checks/api/TruncatedStringTest.java
  src/test/java/io/jenkins/plugins/checks/status/BuildStatusChecksPublisherITest.java
Labels: bug

#98 JENKINS-65262 Add ability to disable graph analyzer
  pom.xml
  src/main/java/io/jenkins/plugins/checks/status/AbstractStatusChecksProperties.java
  src/main/java/io/jenkins/plugins/checks/status/BuildStatusChecksPublisher.java
Labels: enhancement

#106 docs: minor doc update with the correct class
  docs/consumers-guide.md
Labels: documentation
