Repository jenkinsci/checks-api-plugin, pull requests merged in 2025-02, with the labels that each got.

#270 Change default behavior to truncate Checks text from start when maxSize present
  src/main/java/io/jenkins/plugins/checks/api/ChecksOutput.java
  src/test/java/io/jenkins/plugins/checks/api/ChecksOutputTest.java
Labels: enhancement

#272 Changed the truncate summary to cut build logs from top
  src/main/java/io/jenkins/plugins/checks/api/ChecksOutput.java
  src/main/java/io/jenkins/plugins/checks/status/FlowExecutionAnalyzer.java
  src/test/java/io/jenkins/plugins/checks/api/ChecksOutputTest.java
  src/test/java/io/jenkins/plugins/checks/status/BuildStatusChecksPublisherITest.java
Labels: enhancement

#273 Require 2.479.1 or newer
  pom.xml
  src/main/java/io/jenkins/plugins/checks/api/TruncatedString.java
  src/main/java/io/jenkins/plugins/checks/status/BuildStatusChecksPublisher.java
  src/test/java/io/jenkins/plugins/checks/status/BuildStatusChecksPublisherITest.java
  src/test/java/io/jenkins/plugins/checks/steps/WithChecksStepITest.java
  src/test/java/io/jenkins/plugins/checks/util/CapturingChecksPublisher.java
  src/test/java/io/jenkins/plugins/checks/util/LoggingChecksPublisher.java
Labels: internal

#274 Enable automated releases
  .github/release-drafter.yml
  .github/workflows/cd.yaml
  .github/workflows/release-drafter.yml
  .mvn/maven.config
  pom.xml
Labels: developer
